// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTEZG6KHIJfPLltIAKu0WnPAXkig_6ys0',
    appId: '1:656241231361:web:3b5c177fbeb0c3381a2200',
    messagingSenderId: '656241231361',
    projectId: 'techconnect-42543',
    authDomain: 'techconnect-42543.firebaseapp.com',
    storageBucket: 'techconnect-42543.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMD608dOl90CeqUAR0Pk2HeUu2ZsGKn10',
    appId: '1:656241231361:android:4b8a852a0bb254361a2200',
    messagingSenderId: '656241231361',
    projectId: 'techconnect-42543',
    storageBucket: 'techconnect-42543.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkwM3NJUHtULROM5jdtyTBEXcE9jDsm9E',
    appId: '1:656241231361:ios:fca8109760e0faee1a2200',
    messagingSenderId: '656241231361',
    projectId: 'techconnect-42543',
    storageBucket: 'techconnect-42543.appspot.com',
    iosBundleId: 'com.example.techConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkwM3NJUHtULROM5jdtyTBEXcE9jDsm9E',
    appId: '1:656241231361:ios:4ce843830ced09ab1a2200',
    messagingSenderId: '656241231361',
    projectId: 'techconnect-42543',
    storageBucket: 'techconnect-42543.appspot.com',
    iosBundleId: 'com.example.techConnect.RunnerTests',
  );
}
